# Generated by Django 4.2.3 on 2023-08-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('Provincia', models.CharField(blank=True, max_length=32, null=True)),
                ('Region', models.CharField(blank=True, max_length=32, null=True)),
                ('Fecha_creacion', models.CharField(blank=True, max_length=32, null=True)),
                ('Telefono_contacto', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='infoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Código', models.CharField(blank=True, max_length=32, null=True)),
                ('Descripción', models.CharField(blank=True, max_length=32, null=True)),
                ('Precio_venta', models.CharField(blank=True, max_length=32, null=True)),
                ('Cantidad', models.CharField(blank=True, max_length=32, null=True)),
                ('Tienda_relacionada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.infotienda')),
            ],
        ),
    ]
